apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-gestaoUsuarios
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-gestaoUsuarios
  template:
    metadata:
      labels:
        app: ms-gestaoUsuarios
    spec:
      containers:
      - name: ms-gestaoUsuarios
        image: ms-gestao-usuarios:0.0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ms-gestaoUsuarios-service
spec:
  selector:
    app: ms-gestaoUsuarios-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
