apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-gestao-usuarios
  namespace: ms-gestao-usuarios-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-gestao-usuarios
  template:
    metadata:
      labels:
        app: ms-gestao-usuarios
    spec:
      containers:
        - name: ms-gestao-usuarios
          image: $ECR_REGISTRY/$ECR_REPOSITORY:latest
          ports:
            - containerPort: 8989
          resources:
            requests:
              cpu: 500m       # Solicita 100 milicores de CPU
              memory: 256Mi   # Solicita 256 Mebibytes de memória
            limits:
              cpu: 1000m       # Limita a 200 milicores de CPU
              memory: 512Mi   # Limita a 512 Mebibytes de memória
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8989
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8989
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
